// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import AutosaveController from "controllers/autosave_controller"
application.register("autosave", AutosaveController)

import CollapsibleController from "controllers/collapsible_controller"
application.register("collapsible", CollapsibleController)

import FlashMessageController from "controllers/flash_message_controller"
application.register("flash-message", FlashMessageController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import LexxyEditorController from "controllers/lexxy_editor_controller"
application.register("lexxy-editor", LexxyEditorController)

import SidebarController from "controllers/sidebar_controller"
application.register("sidebar", SidebarController)

import TabsController from "controllers/tabs_controller"
application.register("tabs", TabsController)

import TooltipController from "controllers/tooltip_controller"
application.register("tooltip", TooltipController)

import UnifiedEntryController from "controllers/unified_entry_controller"
application.register("unified-entry", UnifiedEntryController)
