// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutosaveController from "./autosave_controller"
application.register("autosave", AutosaveController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import CollapsibleController from "./collapsible_controller"
application.register("collapsible", CollapsibleController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FlashMessageController from "./flash_message_controller"
application.register("flash-message", FlashMessageController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InsightsController from "./insights_controller"
application.register("insights", InsightsController)

import LexxyEditorController from "./lexxy_editor_controller"
application.register("lexxy-editor", LexxyEditorController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import UnifiedEntryController from "./unified_entry_controller"
application.register("unified-entry", UnifiedEntryController)
